version: '3.9'

services:
  grafana:
    image: grafana/grafana-oss:9.2.3
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards/nodes/node-exporter-full_rev31.json:/etc/grafana/provisioning/dashboards/nodes/node-exporter-full_rev31.json
      - ./grafana/dashboards/containers/docker-container-monitor.json:/etc/grafana/provisioning/dashboards/containers/docker-container-monitor.json
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: dev_password_only
    ports:
      - 3000:3000
    networks:
      monitoring:

  prometheus:
    image: prom/prometheus:v2.38.0
    user: root
    volumes:
      - prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      monitoring:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    command:
      - '-allow_dynamic_housekeeping=false'
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker
      - /dev/disk/:/dev/disk:ro
    networks:
      monitoring:

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    hostname: "{{.Node.ID}}"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      monitoring:

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
