version: '3.9'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    command:
      - '-allow_dynamic_housekeeping=false'
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker
      - /dev/disk/:/dev/disk:ro
    networks:
      monitoring:

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    hostname: "{{.Node.ID}}"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      monitoring:

networks:
  monitoring:
