services:
  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:v8.1.1
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db:27017/openhim"
      mongo_atnaUrl: "mongodb://mongo-db:27017/openhim"
      authentication_enableCustomTokenAuthentication: "true"
      NODE_ENV: "development"
      logger_capSize: "1000"
      logger_logToDB: "false"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - openhim
      - monitoring
    healthcheck:
     test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:80"
    healthcheck:
     test: "curl -sS http://openhim-console || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3
  
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"

volumes:
  mongo-data:

networks:
  openhim:
