global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  # Create a job for reading metrics from nodes
  - job_name: "node-exporter"
    static_configs:
      - targets: ["<ip>:9100"]

  # Create a job for reading metrics from containers
  - job_name: "cadvisor"
    static_configs:
      - targets: ["<ip>:8080"]

  # Create a job for reading openhim metrics
  - job_name: "openhim"
    tls_config:
      insecure_skip_verify: true
    scheme: "https"
    static_configs:
      - targets: ["<ip>:8080"]
